import { useEffect, useRef } from 'react'
import maplibregl, { type GeoJSONSource, type Map } from 'maplibre-gl'
import type { FeatureCollection, Point } from 'geojson'
import 'maplibre-gl/dist/maplibre-gl.css'
import type { Incident } from './types'

interface Props { incidents: Incident[]; selectedId: string | null; onSelect: (id: string) => void }
const style: maplibregl.StyleSpecification = { version: 8, sources: { osm: { type: 'raster', tiles: ['https://tile.openstreetmap.org/{z}/{x}/{y}.png'], tileSize: 256, attribution: '© OpenStreetMap contributors' } }, layers: [{ id: 'osm', type: 'raster', source: 'osm', paint: { 'raster-saturation': -0.75, 'raster-brightness-max': 0.68, 'raster-contrast': 0.25 } }] }
export function IncidentMap({ incidents, selectedId, onSelect }: Props) {
  const container = useRef<HTMLDivElement>(null), mapRef = useRef<Map | null>(null), selectRef = useRef(onSelect)
  useEffect(() => { selectRef.current = onSelect }, [onSelect])
  useEffect(() => { if (!container.current || mapRef.current) return; const map = new maplibregl.Map({ container: container.current, style, center: [5, 20], zoom: 1.4, minZoom: 1, maxZoom: 12, attributionControl: false }); map.addControl(new maplibregl.NavigationControl({ showCompass: false }), 'bottom-left'); map.addControl(new maplibregl.AttributionControl({ compact: true })); map.on('load', () => { map.addSource('incidents', { type: 'geojson', data: { type: 'FeatureCollection', features: [] }, cluster: true, clusterMaxZoom: 6, clusterRadius: 46 }); map.addLayer({ id: 'clusters', type: 'circle', source: 'incidents', filter: ['has', 'point_count'], paint: { 'circle-color': '#e6a23c', 'circle-radius': ['step', ['get', 'point_count'], 18, 25, 23, 100, 28], 'circle-stroke-color': '#141b22', 'circle-stroke-width': 3 } }); map.addLayer({ id: 'cluster-count', type: 'symbol', source: 'incidents', filter: ['has', 'point_count'], layout: { 'text-field': ['get', 'point_count_abbreviated'], 'text-size': 12 }, paint: { 'text-color': '#101820' } }); map.addLayer({ id: 'events', type: 'circle', source: 'incidents', filter: ['!', ['has', 'point_count']], paint: { 'circle-radius': ['match', ['get', 'severity'], 'CRITICAL', 10, 'HIGH', 8, 6], 'circle-color': ['match', ['get', 'severity'], 'CRITICAL', '#ff5b4d', 'HIGH', '#f29f38', 'MODERATE', '#e5c35b', '#63a6a1'], 'circle-stroke-color': '#f4f7f8', 'circle-stroke-width': 2 } }); map.on('click', 'clusters', async e => { const feature = map.queryRenderedFeatures(e.point, { layers: ['clusters'] })[0]; const source = map.getSource('incidents') as GeoJSONSource; const zoom = await source.getClusterExpansionZoom(Number(feature.properties?.cluster_id)); map.easeTo({ center: (feature.geometry as Point).coordinates as [number, number], zoom }) }); map.on('click', 'events', e => { const id = e.features?.[0]?.properties?.id; if (id) selectRef.current(id) }); for (const layer of ['clusters', 'events']) { map.on('mouseenter', layer, () => map.getCanvas().style.cursor = 'pointer'); map.on('mouseleave', layer, () => map.getCanvas().style.cursor = '') } }); mapRef.current = map; return () => { map.remove(); mapRef.current = null } }, [])
  useEffect(() => { const collection: FeatureCollection = { type: 'FeatureCollection', features: incidents.map(item => ({ type: 'Feature', geometry: { type: 'Point', coordinates: [item.location.longitude, item.location.latitude] }, properties: { id: item.id, severity: item.severity, type: item.type, title: item.title } })) }; const update = () => { (mapRef.current?.getSource('incidents') as GeoJSONSource | undefined)?.setData(collection) }; if (mapRef.current?.loaded()) update(); else mapRef.current?.once('load', update) }, [incidents])
  useEffect(() => { const map = mapRef.current; if (!map?.getLayer('events')) return; const item = incidents.find(i => i.id === selectedId); if (item) map.easeTo({ center: [item.location.longitude, item.location.latitude], zoom: Math.max(map.getZoom(), 4), padding: { right: window.innerWidth > 768 ? 380 : 0, top: 0, bottom: 0, left: 0 } }) }, [selectedId, incidents])
  return <div className="map" ref={container} role="application" aria-label={`Interactive global incident map with ${incidents.length} events`} />
}
